In [1]:
#importing the pandas library
import pandas as pd

In [2]:
#reading the file
df = pd.read_csv('../data-companywise/raw_data/ADBL.csv')
df

,published_date,open,high,low,close,per_change,traded_quantity,traded_amount,status
0,2010-09-16,117.0,122.0,116.0,120.0,NaN,5280.0,0.00,0
1,2010-09-19,120.0,120.0,116.0,118.0,-1.67,2648.0,0.00,0
2,2010-09-20,118.0,119.0,116.0,118.0,0.00,2346.0,0.00,0
3,2010-09-21,118.0,118.0,115.0,116.0,-1.69,7160.0,0.00,0
4,2010-09-23,116.0,120.0,117.0,120.0,3.45,8417.0,0.00,0
...,...,...,...,...,...,...,...,...,...
3525,2026-02-24,292.0,297.8,291.0,293.0,0.17,18006.0,5270482.30,1
3526,2026-02-25,293.5,295.5,291.0,294.6,0.55,36465.0,10663448.10,1
3527,2026-02-26,300.4,300.4,292.3,298.0,1.15,21933.0,6475022.88,-1
3528,2026-03-01,295.0,305.0,291.1,302.6,1.54,64794.0,19514957.40,1
3529,2026-03-03,308.6,308.6,297.1,305.0,0.79,47965.0,14601174.90,-1

In [3]:
# Rename specific columns to the "Perfect Schema"
df = df.rename(columns={
    'published_date': 'date',
    'traded_quantity': 'volume',
    'traded_amount': 'turnover',
    'per_change': 'price_change_pct'
})

In [4]:
df['date'] = pd.to_datetime(df['date'])   # convert first
df['year'] = df['date'].dt.year

In [5]:
df

,date,open,high,low,close,price_change_pct,volume,turnover,status,year
0,2010-09-16,117.0,122.0,116.0,120.0,NaN,5280.0,0.00,0,2010
1,2010-09-19,120.0,120.0,116.0,118.0,-1.67,2648.0,0.00,0,2010
2,2010-09-20,118.0,119.0,116.0,118.0,0.00,2346.0,0.00,0,2010
3,2010-09-21,118.0,118.0,115.0,116.0,-1.69,7160.0,0.00,0,2010
4,2010-09-23,116.0,120.0,117.0,120.0,3.45,8417.0,0.00,0,2010
...,...,...,...,...,...,...,...,...,...,...
3525,2026-02-24,292.0,297.8,291.0,293.0,0.17,18006.0,5270482.30,1,2026
3526,2026-02-25,293.5,295.5,291.0,294.6,0.55,36465.0,10663448.10,1,2026
3527,2026-02-26,300.4,300.4,292.3,298.0,1.15,21933.0,6475022.88,-1,2026
3528,2026-03-01,295.0,305.0,291.1,302.6,1.54,64794.0,19514957.40,1,2026
3529,2026-03-03,308.6,308.6,297.1,305.0,0.79,47965.0,14601174.90,-1,2026

In [6]:
#resetting index
df.reset_index(drop= True, inplace = True)
df

,date,open,high,low,close,price_change_pct,volume,turnover,status,year
0,2010-09-16,117.0,122.0,116.0,120.0,NaN,5280.0,0.00,0,2010
1,2010-09-19,120.0,120.0,116.0,118.0,-1.67,2648.0,0.00,0,2010
2,2010-09-20,118.0,119.0,116.0,118.0,0.00,2346.0,0.00,0,2010
3,2010-09-21,118.0,118.0,115.0,116.0,-1.69,7160.0,0.00,0,2010
4,2010-09-23,116.0,120.0,117.0,120.0,3.45,8417.0,0.00,0,2010
...,...,...,...,...,...,...,...,...,...,...
3525,2026-02-24,292.0,297.8,291.0,293.0,0.17,18006.0,5270482.30,1,2026
3526,2026-02-25,293.5,295.5,291.0,294.6,0.55,36465.0,10663448.10,1,2026
3527,2026-02-26,300.4,300.4,292.3,298.0,1.15,21933.0,6475022.88,-1,2026
3528,2026-03-01,295.0,305.0,291.1,302.6,1.54,64794.0,19514957.40,1,2026
3529,2026-03-03,308.6,308.6,297.1,305.0,0.79,47965.0,14601174.90,-1,2026

In [7]:

fundamental_data = {
    'year': [2022, 2023, 2024, 2025], # FY 78/79, 79/80, 80/81, 81/82
    'eps': [21.85, 10.32, 18.25, 23.44],  # Adjusted for Preference Dividend
    'pe-ratio': [15.24, 34.60, 14.58, 12.63], # Based on Fiscal Year-end prices
    'roe': [12.10, 5.64, 9.88, 11.95],     # Return on Equity (%)
    'dividend': [13.00, 11.00, 10.53, 13.00]} # Total % (Bonus + Cash)

df_fundamental = pd.DataFrame(fundamental_data)
df_fundamental

   year    eps  pe-ratio    roe  dividend
0  2022  21.85     15.24  12.10     13.00
1  2023  10.32     34.60   5.64     11.00
2  2024  18.25     14.58   9.88     10.53
3  2025  23.44     12.63  11.95     13.00

In [8]:
# #merging
df = pd.merge(df, df_fundamental, on='year',how= 'left')
df

,date,open,high,low,close,price_change_pct,volume,turnover,status,year,eps,pe-ratio,roe,dividend
0,2010-09-16,117.0,122.0,116.0,120.0,NaN,5280.0,0.00,0,2010,NaN,NaN,NaN,NaN
1,2010-09-19,120.0,120.0,116.0,118.0,-1.67,2648.0,0.00,0,2010,NaN,NaN,NaN,NaN
2,2010-09-20,118.0,119.0,116.0,118.0,0.00,2346.0,0.00,0,2010,NaN,NaN,NaN,NaN
3,2010-09-21,118.0,118.0,115.0,116.0,-1.69,7160.0,0.00,0,2010,NaN,NaN,NaN,NaN
4,2010-09-23,116.0,120.0,117.0,120.0,3.45,8417.0,0.00,0,2010,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3525,2026-02-24,292.0,297.8,291.0,293.0,0.17,18006.0,5270482.30,1,2026,NaN,NaN,NaN,NaN
3526,2026-02-25,293.5,295.5,291.0,294.6,0.55,36465.0,10663448.10,1,2026,NaN,NaN,NaN,NaN
3527,2026-02-26,300.4,300.4,292.3,298.0,1.15,21933.0,6475022.88,-1,2026,NaN,NaN,NaN,NaN
3528,2026-03-01,295.0,305.0,291.1,302.6,1.54,64794.0,19514957.40,1,2026,NaN,NaN,NaN,NaN
3529,2026-03-03,308.6,308.6,297.1,305.0,0.79,47965.0,14601174.90,-1,2026,NaN,NaN,NaN,NaN

In [9]:
df = df.copy()
df.to_csv('../data-companywise/processed_data/ADBL.csv', index = False)