In [1]:
#importing the pandas library
import pandas as pd

In [2]:
df = pd.read_csv('../data-companywise/raw_data/MNBBL.csv')
df

,published_date,open,high,low,close,per_change,traded_quantity,traded_amount,status
0,2011-12-27,148.0,148.0,146.0,146.0,NaN,380.0,55700.0,0
1,2011-12-28,146.0,144.0,141.0,142.0,-2.74,670.0,95300.0,0
2,2011-12-29,142.0,144.0,143.0,144.0,1.41,1510.0,217330.0,0
3,2012-01-01,144.0,150.0,146.0,146.0,1.39,1820.0,268890.0,0
4,2012-01-02,146.0,150.0,142.0,148.0,1.37,450.0,65460.0,0
...,...,...,...,...,...,...,...,...,...
3174,2026-02-24,356.0,362.0,356.0,359.9,0.59,19432.0,6977614.8,1
3175,2026-02-25,360.0,363.4,358.4,361.5,0.44,28787.0,10377478.8,1
3176,2026-02-26,361.5,363.9,359.5,360.4,-0.30,31566.0,11413191.3,-1
3177,2026-03-01,360.0,366.2,356.3,366.0,1.55,44163.0,16057330.1,1
3178,2026-03-03,366.0,374.0,362.0,371.0,1.37,43932.0,16263371.3,1

In [3]:
df.drop(columns = 'status', inplace = True)
df

,published_date,open,high,low,close,per_change,traded_quantity,traded_amount
0,2011-12-27,148.0,148.0,146.0,146.0,NaN,380.0,55700.0
1,2011-12-28,146.0,144.0,141.0,142.0,-2.74,670.0,95300.0
2,2011-12-29,142.0,144.0,143.0,144.0,1.41,1510.0,217330.0
3,2012-01-01,144.0,150.0,146.0,146.0,1.39,1820.0,268890.0
4,2012-01-02,146.0,150.0,142.0,148.0,1.37,450.0,65460.0
...,...,...,...,...,...,...,...,...
3174,2026-02-24,356.0,362.0,356.0,359.9,0.59,19432.0,6977614.8
3175,2026-02-25,360.0,363.4,358.4,361.5,0.44,28787.0,10377478.8
3176,2026-02-26,361.5,363.9,359.5,360.4,-0.30,31566.0,11413191.3
3177,2026-03-01,360.0,366.2,356.3,366.0,1.55,44163.0,16057330.1
3178,2026-03-03,366.0,374.0,362.0,371.0,1.37,43932.0,16263371.3

In [4]:
# Rename specific columns to the "Perfect Schema"
df = df.rename(columns={
    'published_date': 'date',
    'traded_quantity': 'volume',
    'traded_amount': 'turnover',
    'per_change': 'price_change_pct'
})

In [5]:
df

,date,open,high,low,close,price_change_pct,volume,turnover
0,2011-12-27,148.0,148.0,146.0,146.0,NaN,380.0,55700.0
1,2011-12-28,146.0,144.0,141.0,142.0,-2.74,670.0,95300.0
2,2011-12-29,142.0,144.0,143.0,144.0,1.41,1510.0,217330.0
3,2012-01-01,144.0,150.0,146.0,146.0,1.39,1820.0,268890.0
4,2012-01-02,146.0,150.0,142.0,148.0,1.37,450.0,65460.0
...,...,...,...,...,...,...,...,...
3174,2026-02-24,356.0,362.0,356.0,359.9,0.59,19432.0,6977614.8
3175,2026-02-25,360.0,363.4,358.4,361.5,0.44,28787.0,10377478.8
3176,2026-02-26,361.5,363.9,359.5,360.4,-0.30,31566.0,11413191.3
3177,2026-03-01,360.0,366.2,356.3,366.0,1.55,44163.0,16057330.1
3178,2026-03-03,366.0,374.0,362.0,371.0,1.37,43932.0,16263371.3

In [6]:
df['date'] = pd.to_datetime(df['date'])   # convert first
df['year'] = df['date'].dt.year

In [7]:
df

,date,open,high,low,close,price_change_pct,volume,turnover,year
0,2011-12-27,148.0,148.0,146.0,146.0,NaN,380.0,55700.0,2011
1,2011-12-28,146.0,144.0,141.0,142.0,-2.74,670.0,95300.0,2011
2,2011-12-29,142.0,144.0,143.0,144.0,1.41,1510.0,217330.0,2011
3,2012-01-01,144.0,150.0,146.0,146.0,1.39,1820.0,268890.0,2012
4,2012-01-02,146.0,150.0,142.0,148.0,1.37,450.0,65460.0,2012
...,...,...,...,...,...,...,...,...,...
3174,2026-02-24,356.0,362.0,356.0,359.9,0.59,19432.0,6977614.8,2026
3175,2026-02-25,360.0,363.4,358.4,361.5,0.44,28787.0,10377478.8,2026
3176,2026-02-26,361.5,363.9,359.5,360.4,-0.30,31566.0,11413191.3,2026
3177,2026-03-01,360.0,366.2,356.3,366.0,1.55,44163.0,16057330.1,2026
3178,2026-03-03,366.0,374.0,362.0,371.0,1.37,43932.0,16263371.3,2026

In [8]:
#filtering the data from 2022
df['date'] = pd.to_datetime(df['date'])
df=df[df['date'].dt.year >= 2022].copy()
df.to_csv('NABIL.csv', index= False)

In [9]:
df

,date,open,high,low,close,price_change_pct,volume,turnover,year
2215,2022-01-02,504.9,512.0,495.0,510.0,3.03,47768.0,24052044.8,2022
2216,2022-01-03,520.2,524.0,510.0,515.0,0.98,36360.0,18769060.7,2022
2217,2022-01-04,515.0,532.0,510.0,530.0,2.91,82464.0,43215859.8,2022
2218,2022-01-05,530.0,547.8,522.5,528.0,-0.38,83036.0,44498959.1,2022
2219,2022-01-06,525.0,536.0,525.0,536.0,1.52,48131.0,25594951.2,2022
...,...,...,...,...,...,...,...,...,...
3174,2026-02-24,356.0,362.0,356.0,359.9,0.59,19432.0,6977614.8,2026
3175,2026-02-25,360.0,363.4,358.4,361.5,0.44,28787.0,10377478.8,2026
3176,2026-02-26,361.5,363.9,359.5,360.4,-0.30,31566.0,11413191.3,2026
3177,2026-03-01,360.0,366.2,356.3,366.0,1.55,44163.0,16057330.1,2026
3178,2026-03-03,366.0,374.0,362.0,371.0,1.37,43932.0,16263371.3,2026

In [10]:
#resetting index
df.reset_index(drop= True, inplace = True)
df

,date,open,high,low,close,price_change_pct,volume,turnover,year
0,2022-01-02,504.9,512.0,495.0,510.0,3.03,47768.0,24052044.8,2022
1,2022-01-03,520.2,524.0,510.0,515.0,0.98,36360.0,18769060.7,2022
2,2022-01-04,515.0,532.0,510.0,530.0,2.91,82464.0,43215859.8,2022
3,2022-01-05,530.0,547.8,522.5,528.0,-0.38,83036.0,44498959.1,2022
4,2022-01-06,525.0,536.0,525.0,536.0,1.52,48131.0,25594951.2,2022
...,...,...,...,...,...,...,...,...,...
959,2026-02-24,356.0,362.0,356.0,359.9,0.59,19432.0,6977614.8,2026
960,2026-02-25,360.0,363.4,358.4,361.5,0.44,28787.0,10377478.8,2026
961,2026-02-26,361.5,363.9,359.5,360.4,-0.30,31566.0,11413191.3,2026
962,2026-03-01,360.0,366.2,356.3,366.0,1.55,44163.0,16057330.1,2026
963,2026-03-03,366.0,374.0,362.0,371.0,1.37,43932.0,16263371.3,2026

In [11]:
#filtering the data from 2022
df['date'] = pd.to_datetime(df['date'])
df=df[df['date'].dt.year >= 2022].copy()
df.to_csv('NABIL.csv', index= False)

In [12]:
df

,date,open,high,low,close,price_change_pct,volume,turnover,year
0,2022-01-02,504.9,512.0,495.0,510.0,3.03,47768.0,24052044.8,2022
1,2022-01-03,520.2,524.0,510.0,515.0,0.98,36360.0,18769060.7,2022
2,2022-01-04,515.0,532.0,510.0,530.0,2.91,82464.0,43215859.8,2022
3,2022-01-05,530.0,547.8,522.5,528.0,-0.38,83036.0,44498959.1,2022
4,2022-01-06,525.0,536.0,525.0,536.0,1.52,48131.0,25594951.2,2022
...,...,...,...,...,...,...,...,...,...
959,2026-02-24,356.0,362.0,356.0,359.9,0.59,19432.0,6977614.8,2026
960,2026-02-25,360.0,363.4,358.4,361.5,0.44,28787.0,10377478.8,2026
961,2026-02-26,361.5,363.9,359.5,360.4,-0.30,31566.0,11413191.3,2026
962,2026-03-01,360.0,366.2,356.3,366.0,1.55,44163.0,16057330.1,2026
963,2026-03-03,366.0,374.0,362.0,371.0,1.37,43932.0,16263371.3,2026

In [13]:

#adding some fundamental signals
fundamental_data = {
    'year': [2022, 2023, 2024, 2025],
    'eps': [29.61, 23.36, 18.70, 16.80],  # NPR (Annualized from Q1/Q2 2082/83)
    'pe-ratio': [15.20, 16.50, 19.52, 21.55], 
    'roe': [16.82, 13.90, 13.50, 11.10],  # Statutory ROE %
    'dividend': [18.5, 14.2,10.2,18.2] # 2024 Actual: 18.2% (13.53% Bonus)
}
df_fundamental = pd.DataFrame(fundamental_data)
df_fundamental

   year    eps  pe-ratio    roe  dividend
0  2022  29.61     15.20  16.82      18.5
1  2023  23.36     16.50  13.90      14.2
2  2024  18.70     19.52  13.50      10.2
3  2025  16.80     21.55  11.10      18.2

In [14]:
# #merging
df = pd.merge(df, df_fundamental, on='year',how= 'left')
df

,date,open,high,low,close,price_change_pct,volume,turnover,year,eps,pe-ratio,roe,dividend
0,2022-01-02,504.9,512.0,495.0,510.0,3.03,47768.0,24052044.8,2022,29.61,15.2,16.82,18.5
1,2022-01-03,520.2,524.0,510.0,515.0,0.98,36360.0,18769060.7,2022,29.61,15.2,16.82,18.5
2,2022-01-04,515.0,532.0,510.0,530.0,2.91,82464.0,43215859.8,2022,29.61,15.2,16.82,18.5
3,2022-01-05,530.0,547.8,522.5,528.0,-0.38,83036.0,44498959.1,2022,29.61,15.2,16.82,18.5
4,2022-01-06,525.0,536.0,525.0,536.0,1.52,48131.0,25594951.2,2022,29.61,15.2,16.82,18.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
959,2026-02-24,356.0,362.0,356.0,359.9,0.59,19432.0,6977614.8,2026,NaN,NaN,NaN,NaN
960,2026-02-25,360.0,363.4,358.4,361.5,0.44,28787.0,10377478.8,2026,NaN,NaN,NaN,NaN
961,2026-02-26,361.5,363.9,359.5,360.4,-0.30,31566.0,11413191.3,2026,NaN,NaN,NaN,NaN
962,2026-03-01,360.0,366.2,356.3,366.0,1.55,44163.0,16057330.1,2026,NaN,NaN,NaN,NaN
963,2026-03-03,366.0,374.0,362.0,371.0,1.37,43932.0,16263371.3,2026,NaN,NaN,NaN,NaN

In [15]:

df = df.copy()
df.to_csv('../data-companywise/processed_data/MNBBL.csv', index = False)