In [1]:
#importing the pandas library
import pandas as pd

In [2]:
df = pd.read_csv('../../data-companywise/raw_data/MNBBL.csv')
df

,published_date,open,high,low,close,per_change,traded_quantity,traded_amount,status
0,12/27/2011,148.0,148.0,146.0,146.0,NaN,380,55700.0,0
1,12/28/2011,146.0,144.0,141.0,142.0,-2.74,670,95300.0,0
2,12/29/2011,142.0,144.0,143.0,144.0,1.41,1510,217330.0,0
3,1/1/2012,144.0,150.0,146.0,146.0,1.39,1820,268890.0,0
4,1/2/2012,146.0,150.0,142.0,148.0,1.37,450,65460.0,0
...,...,...,...,...,...,...,...,...,...
3178,3/3/2026,366.0,374.0,362.0,371.0,1.37,43932,16263371.3,1
3179,3/9/2026,378.4,386.0,378.4,386.0,4.02,888,338000.0,1
3180,3/10/2026,393.6,407.0,385.0,393.0,1.84,275000,107500000.0,1
3181,3/11/2026,400.0,400.0,385.3,388.0,-1.27,91010,35500000.0,-1
3182,3/12/2026,382.2,394.0,381.3,390.0,0.44,92884,37600000.0,1

In [3]:
df.drop(columns = 'status', inplace = True)
df

,published_date,open,high,low,close,per_change,traded_quantity,traded_amount
0,12/27/2011,148.0,148.0,146.0,146.0,NaN,380,55700.0
1,12/28/2011,146.0,144.0,141.0,142.0,-2.74,670,95300.0
2,12/29/2011,142.0,144.0,143.0,144.0,1.41,1510,217330.0
3,1/1/2012,144.0,150.0,146.0,146.0,1.39,1820,268890.0
4,1/2/2012,146.0,150.0,142.0,148.0,1.37,450,65460.0
...,...,...,...,...,...,...,...,...
3178,3/3/2026,366.0,374.0,362.0,371.0,1.37,43932,16263371.3
3179,3/9/2026,378.4,386.0,378.4,386.0,4.02,888,338000.0
3180,3/10/2026,393.6,407.0,385.0,393.0,1.84,275000,107500000.0
3181,3/11/2026,400.0,400.0,385.3,388.0,-1.27,91010,35500000.0
3182,3/12/2026,382.2,394.0,381.3,390.0,0.44,92884,37600000.0

In [4]:
# Rename specific columns to the "Perfect Schema"
df = df.rename(columns={
    'published_date': 'date',
    'traded_quantity': 'volume',
    'traded_amount': 'turnover',
    'per_change': 'price_change_pct'
})

In [5]:
df

,date,open,high,low,close,price_change_pct,volume,turnover
0,12/27/2011,148.0,148.0,146.0,146.0,NaN,380,55700.0
1,12/28/2011,146.0,144.0,141.0,142.0,-2.74,670,95300.0
2,12/29/2011,142.0,144.0,143.0,144.0,1.41,1510,217330.0
3,1/1/2012,144.0,150.0,146.0,146.0,1.39,1820,268890.0
4,1/2/2012,146.0,150.0,142.0,148.0,1.37,450,65460.0
...,...,...,...,...,...,...,...,...
3178,3/3/2026,366.0,374.0,362.0,371.0,1.37,43932,16263371.3
3179,3/9/2026,378.4,386.0,378.4,386.0,4.02,888,338000.0
3180,3/10/2026,393.6,407.0,385.0,393.0,1.84,275000,107500000.0
3181,3/11/2026,400.0,400.0,385.3,388.0,-1.27,91010,35500000.0
3182,3/12/2026,382.2,394.0,381.3,390.0,0.44,92884,37600000.0

In [6]:
df['date'] = pd.to_datetime(df['date'])   # convert first
df['year'] = df['date'].dt.year

In [7]:
df

,date,open,high,low,close,price_change_pct,volume,turnover,year
0,2011-12-27,148.0,148.0,146.0,146.0,NaN,380,55700.0,2011
1,2011-12-28,146.0,144.0,141.0,142.0,-2.74,670,95300.0,2011
2,2011-12-29,142.0,144.0,143.0,144.0,1.41,1510,217330.0,2011
3,2012-01-01,144.0,150.0,146.0,146.0,1.39,1820,268890.0,2012
4,2012-01-02,146.0,150.0,142.0,148.0,1.37,450,65460.0,2012
...,...,...,...,...,...,...,...,...,...
3178,2026-03-03,366.0,374.0,362.0,371.0,1.37,43932,16263371.3,2026
3179,2026-03-09,378.4,386.0,378.4,386.0,4.02,888,338000.0,2026
3180,2026-03-10,393.6,407.0,385.0,393.0,1.84,275000,107500000.0,2026
3181,2026-03-11,400.0,400.0,385.3,388.0,-1.27,91010,35500000.0,2026
3182,2026-03-12,382.2,394.0,381.3,390.0,0.44,92884,37600000.0,2026

In [8]:
#filtering the data from 2022
df['date'] = pd.to_datetime(df['date'])
df=df[df['date'].dt.year >= 2022].copy()
df.to_csv('NABIL.csv', index= False)

In [9]:
df

,date,open,high,low,close,price_change_pct,volume,turnover,year
2215,2022-01-02,504.9,512.0,495.0,510.0,3.03,47768,24052044.8,2022
2216,2022-01-03,520.2,524.0,510.0,515.0,0.98,36360,18769060.7,2022
2217,2022-01-04,515.0,532.0,510.0,530.0,2.91,82464,43215859.8,2022
2218,2022-01-05,530.0,547.8,522.5,528.0,-0.38,83036,44498959.1,2022
2219,2022-01-06,525.0,536.0,525.0,536.0,1.52,48131,25594951.2,2022
...,...,...,...,...,...,...,...,...,...
3178,2026-03-03,366.0,374.0,362.0,371.0,1.37,43932,16263371.3,2026
3179,2026-03-09,378.4,386.0,378.4,386.0,4.02,888,338000.0,2026
3180,2026-03-10,393.6,407.0,385.0,393.0,1.84,275000,107500000.0,2026
3181,2026-03-11,400.0,400.0,385.3,388.0,-1.27,91010,35500000.0,2026
3182,2026-03-12,382.2,394.0,381.3,390.0,0.44,92884,37600000.0,2026

In [10]:
#resetting index
df.reset_index(drop= True, inplace = True)
df

,date,open,high,low,close,price_change_pct,volume,turnover,year
0,2022-01-02,504.9,512.0,495.0,510.0,3.03,47768,24052044.8,2022
1,2022-01-03,520.2,524.0,510.0,515.0,0.98,36360,18769060.7,2022
2,2022-01-04,515.0,532.0,510.0,530.0,2.91,82464,43215859.8,2022
3,2022-01-05,530.0,547.8,522.5,528.0,-0.38,83036,44498959.1,2022
4,2022-01-06,525.0,536.0,525.0,536.0,1.52,48131,25594951.2,2022
...,...,...,...,...,...,...,...,...,...
963,2026-03-03,366.0,374.0,362.0,371.0,1.37,43932,16263371.3,2026
964,2026-03-09,378.4,386.0,378.4,386.0,4.02,888,338000.0,2026
965,2026-03-10,393.6,407.0,385.0,393.0,1.84,275000,107500000.0,2026
966,2026-03-11,400.0,400.0,385.3,388.0,-1.27,91010,35500000.0,2026
967,2026-03-12,382.2,394.0,381.3,390.0,0.44,92884,37600000.0,2026

In [11]:
#filtering the data from 2022
df['date'] = pd.to_datetime(df['date'])
df=df[df['date'].dt.year >= 2022].copy()
df.to_csv('NABIL.csv', index= False)

In [12]:
df

,date,open,high,low,close,price_change_pct,volume,turnover,year
0,2022-01-02,504.9,512.0,495.0,510.0,3.03,47768,24052044.8,2022
1,2022-01-03,520.2,524.0,510.0,515.0,0.98,36360,18769060.7,2022
2,2022-01-04,515.0,532.0,510.0,530.0,2.91,82464,43215859.8,2022
3,2022-01-05,530.0,547.8,522.5,528.0,-0.38,83036,44498959.1,2022
4,2022-01-06,525.0,536.0,525.0,536.0,1.52,48131,25594951.2,2022
...,...,...,...,...,...,...,...,...,...
963,2026-03-03,366.0,374.0,362.0,371.0,1.37,43932,16263371.3,2026
964,2026-03-09,378.4,386.0,378.4,386.0,4.02,888,338000.0,2026
965,2026-03-10,393.6,407.0,385.0,393.0,1.84,275000,107500000.0,2026
966,2026-03-11,400.0,400.0,385.3,388.0,-1.27,91010,35500000.0,2026
967,2026-03-12,382.2,394.0,381.3,390.0,0.44,92884,37600000.0,2026

In [13]:

#adding some fundamental signals
fundamental_data = {
    'year': [2022, 2023, 2024, 2025],
    'eps': [29.61, 23.36, 18.70, 16.80],  
    'pe-ratio': [15.20, 16.50, 19.52, 21.55], 
    'roe': [16.82, 13.90, 13.50, 11.10],  
    'dividend': [18.5, 14.2,10.2,18.2],
    'net-margin': [10.25, 9.32, 13.92, 16.26],
    'pb-ratio': [2.85, 3.07, 2.70, 2.40],
    'debt-equity': [14.06, 11.98, 9.50, 8.80]
}
df_fundamental = pd.DataFrame(fundamental_data)
df_fundamental

   year    eps  pe-ratio    roe  dividend  net-margin  pb-ratio  debt-equity
0  2022  29.61     15.20  16.82      18.5       10.25      2.85        14.06
1  2023  23.36     16.50  13.90      14.2        9.32      3.07        11.98
2  2024  18.70     19.52  13.50      10.2       13.92      2.70         9.50
3  2025  16.80     21.55  11.10      18.2       16.26      2.40         8.80

In [14]:
# #merging
df = pd.merge(df, df_fundamental, on='year',how= 'left')
df

,date,open,high,low,close,price_change_pct,volume,turnover,year,eps,pe-ratio,roe,dividend,net-margin,pb-ratio,debt-equity
0,2022-01-02,504.9,512.0,495.0,510.0,3.03,47768,24052044.8,2022,29.61,15.2,16.82,18.5,10.25,2.85,14.06
1,2022-01-03,520.2,524.0,510.0,515.0,0.98,36360,18769060.7,2022,29.61,15.2,16.82,18.5,10.25,2.85,14.06
2,2022-01-04,515.0,532.0,510.0,530.0,2.91,82464,43215859.8,2022,29.61,15.2,16.82,18.5,10.25,2.85,14.06
3,2022-01-05,530.0,547.8,522.5,528.0,-0.38,83036,44498959.1,2022,29.61,15.2,16.82,18.5,10.25,2.85,14.06
4,2022-01-06,525.0,536.0,525.0,536.0,1.52,48131,25594951.2,2022,29.61,15.2,16.82,18.5,10.25,2.85,14.06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
963,2026-03-03,366.0,374.0,362.0,371.0,1.37,43932,16263371.3,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
964,2026-03-09,378.4,386.0,378.4,386.0,4.02,888,338000.0,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
965,2026-03-10,393.6,407.0,385.0,393.0,1.84,275000,107500000.0,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
966,2026-03-11,400.0,400.0,385.3,388.0,-1.27,91010,35500000.0,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
967,2026-03-12,382.2,394.0,381.3,390.0,0.44,92884,37600000.0,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:

df = df.copy()
df.to_csv('../../data-companywise/processed_data/MNBBL.csv', index = False)