In [14]:
#importing the pandas library
import pandas as pd

In [15]:
#reading the file
df = pd.read_csv('..//../data-companywise/raw_data/NABIL.csv')
df

,published_date,open,high,low,close,per_change,traded_quantity,traded_amount,status
0,5/15/2011,1091.0,1155.0,1112.0,1155.0,NaN,38,43057.0,0
1,5/16/2011,1155.0,1193.0,1160.0,1193.0,3.29,156,183026.0,0
2,5/18/2011,1193.0,1172.0,1150.0,1172.0,-1.76,939,1087972.0,0
3,5/19/2011,1172.0,1194.0,1155.0,1194.0,1.88,490,573992.0,0
4,5/22/2011,1194.0,1193.0,1178.0,1178.0,-1.34,115,135930.0,0
...,...,...,...,...,...,...,...,...,...
3379,3/3/2026,508.9,508.9,497.0,504.0,1.00,53465,26848394.6,-1
3380,3/9/2026,514.0,545.0,514.0,545.0,8.13,4906,2570000.0,1
3381,3/10/2026,545.0,555.0,528.0,535.0,-1.87,272000,146200000.0,-1
3382,3/11/2026,539.0,539.0,525.0,527.0,-1.46,78574,41600000.0,-1
3383,3/12/2026,522.1,531.7,522.0,529.0,0.38,81850,43200000.0,1

In [16]:
#removing the status column
df.drop(columns ='status',inplace= True)
df

,published_date,open,high,low,close,per_change,traded_quantity,traded_amount
0,5/15/2011,1091.0,1155.0,1112.0,1155.0,NaN,38,43057.0
1,5/16/2011,1155.0,1193.0,1160.0,1193.0,3.29,156,183026.0
2,5/18/2011,1193.0,1172.0,1150.0,1172.0,-1.76,939,1087972.0
3,5/19/2011,1172.0,1194.0,1155.0,1194.0,1.88,490,573992.0
4,5/22/2011,1194.0,1193.0,1178.0,1178.0,-1.34,115,135930.0
...,...,...,...,...,...,...,...,...
3379,3/3/2026,508.9,508.9,497.0,504.0,1.00,53465,26848394.6
3380,3/9/2026,514.0,545.0,514.0,545.0,8.13,4906,2570000.0
3381,3/10/2026,545.0,555.0,528.0,535.0,-1.87,272000,146200000.0
3382,3/11/2026,539.0,539.0,525.0,527.0,-1.46,78574,41600000.0
3383,3/12/2026,522.1,531.7,522.0,529.0,0.38,81850,43200000.0

In [17]:
# Rename specific columns to the "Perfect Schema"
df = df.rename(columns={
    'published_date': 'date',
    'traded_quantity': 'volume',
    'traded_amount': 'turnover',
    'per_change': 'price_change_pct'
})

In [18]:
df

,date,open,high,low,close,price_change_pct,volume,turnover
0,5/15/2011,1091.0,1155.0,1112.0,1155.0,NaN,38,43057.0
1,5/16/2011,1155.0,1193.0,1160.0,1193.0,3.29,156,183026.0
2,5/18/2011,1193.0,1172.0,1150.0,1172.0,-1.76,939,1087972.0
3,5/19/2011,1172.0,1194.0,1155.0,1194.0,1.88,490,573992.0
4,5/22/2011,1194.0,1193.0,1178.0,1178.0,-1.34,115,135930.0
...,...,...,...,...,...,...,...,...
3379,3/3/2026,508.9,508.9,497.0,504.0,1.00,53465,26848394.6
3380,3/9/2026,514.0,545.0,514.0,545.0,8.13,4906,2570000.0
3381,3/10/2026,545.0,555.0,528.0,535.0,-1.87,272000,146200000.0
3382,3/11/2026,539.0,539.0,525.0,527.0,-1.46,78574,41600000.0
3383,3/12/2026,522.1,531.7,522.0,529.0,0.38,81850,43200000.0

In [19]:
df['date'] = pd.to_datetime(df['date'])   # convert first
df['year'] = df['date'].dt.year

In [20]:
df

,date,open,high,low,close,price_change_pct,volume,turnover,year
0,2011-05-15,1091.0,1155.0,1112.0,1155.0,NaN,38,43057.0,2011
1,2011-05-16,1155.0,1193.0,1160.0,1193.0,3.29,156,183026.0,2011
2,2011-05-18,1193.0,1172.0,1150.0,1172.0,-1.76,939,1087972.0,2011
3,2011-05-19,1172.0,1194.0,1155.0,1194.0,1.88,490,573992.0,2011
4,2011-05-22,1194.0,1193.0,1178.0,1178.0,-1.34,115,135930.0,2011
...,...,...,...,...,...,...,...,...,...
3379,2026-03-03,508.9,508.9,497.0,504.0,1.00,53465,26848394.6,2026
3380,2026-03-09,514.0,545.0,514.0,545.0,8.13,4906,2570000.0,2026
3381,2026-03-10,545.0,555.0,528.0,535.0,-1.87,272000,146200000.0,2026
3382,2026-03-11,539.0,539.0,525.0,527.0,-1.46,78574,41600000.0,2026
3383,2026-03-12,522.1,531.7,522.0,529.0,0.38,81850,43200000.0,2026

In [21]:
#filtering the data from 2022
df['date'] = pd.to_datetime(df['date'])
df=df[df['date'].dt.year >= 2022].copy()

In [22]:
df

,date,open,high,low,close,price_change_pct,volume,turnover,year
2415,2022-01-02,1107.0,1151.5,1086.0,1144.0,5.41,263845,297049298.9,2022
2416,2022-01-03,1150.0,1160.0,1137.0,1137.0,-0.61,130041,149363282.6,2022
2417,2022-01-04,1137.0,1139.0,1117.2,1119.0,-1.58,116739,130969035.9,2022
2418,2022-01-05,1122.0,1138.0,1110.0,1111.9,-0.63,75462,84317711.8,2022
2419,2022-01-06,1111.0,1123.0,1099.6,1114.0,0.19,67780,75380074.6,2022
...,...,...,...,...,...,...,...,...,...
3379,2026-03-03,508.9,508.9,497.0,504.0,1.00,53465,26848394.6,2026
3380,2026-03-09,514.0,545.0,514.0,545.0,8.13,4906,2570000.0,2026
3381,2026-03-10,545.0,555.0,528.0,535.0,-1.87,272000,146200000.0,2026
3382,2026-03-11,539.0,539.0,525.0,527.0,-1.46,78574,41600000.0,2026
3383,2026-03-12,522.1,531.7,522.0,529.0,0.38,81850,43200000.0,2026

In [23]:
#resetting index
df.reset_index(drop= True, inplace = True)
df

,date,open,high,low,close,price_change_pct,volume,turnover,year
0,2022-01-02,1107.0,1151.5,1086.0,1144.0,5.41,263845,297049298.9,2022
1,2022-01-03,1150.0,1160.0,1137.0,1137.0,-0.61,130041,149363282.6,2022
2,2022-01-04,1137.0,1139.0,1117.2,1119.0,-1.58,116739,130969035.9,2022
3,2022-01-05,1122.0,1138.0,1110.0,1111.9,-0.63,75462,84317711.8,2022
4,2022-01-06,1111.0,1123.0,1099.6,1114.0,0.19,67780,75380074.6,2022
...,...,...,...,...,...,...,...,...,...
964,2026-03-03,508.9,508.9,497.0,504.0,1.00,53465,26848394.6,2026
965,2026-03-09,514.0,545.0,514.0,545.0,8.13,4906,2570000.0,2026
966,2026-03-10,545.0,555.0,528.0,535.0,-1.87,272000,146200000.0,2026
967,2026-03-11,539.0,539.0,525.0,527.0,-1.46,78574,41600000.0,2026
968,2026-03-12,522.1,531.7,522.0,529.0,0.38,81850,43200000.0,2026

In [24]:
#adding some fundamental signals
fundamental_data = {
    'year': [2022, 2023, 2024, 2025], 
    'eps': [37.42, 30.25, 25.84, 25.97],  
    'pe-ratio': [21.50, 19.80, 19.13, 19.13], 
    'roe': [14.80, 11.60, 10.50, 11.20],  
    'dividend': [30.00, 11.00, 10.00, 12.50], 
    'net-margin': [14.46, 15.25, 17.61, 22.02],
    'pb-ratio': [2.10, 3.20, 2.20, 2.35],
    'debt-equity': [9.10, 9.50, 9.80, 8.50]
}
df_fundamental = pd.DataFrame(fundamental_data)
df_fundamental

   year    eps  pe-ratio   roe  dividend  net-margin  pb-ratio  debt-equity
0  2022  37.42     21.50  14.8      30.0       14.46      2.10          9.1
1  2023  30.25     19.80  11.6      11.0       15.25      3.20          9.5
2  2024  25.84     19.13  10.5      10.0       17.61      2.20          9.8
3  2025  25.97     19.13  11.2      12.5       22.02      2.35          8.5

In [25]:
# #merging
df = pd.merge(df, df_fundamental, on='year',how= 'left')
df

,date,open,high,low,close,price_change_pct,volume,turnover,year,eps,pe-ratio,roe,dividend,net-margin,pb-ratio,debt-equity
0,2022-01-02,1107.0,1151.5,1086.0,1144.0,5.41,263845,297049298.9,2022,37.42,21.5,14.8,30.0,14.46,2.1,9.1
1,2022-01-03,1150.0,1160.0,1137.0,1137.0,-0.61,130041,149363282.6,2022,37.42,21.5,14.8,30.0,14.46,2.1,9.1
2,2022-01-04,1137.0,1139.0,1117.2,1119.0,-1.58,116739,130969035.9,2022,37.42,21.5,14.8,30.0,14.46,2.1,9.1
3,2022-01-05,1122.0,1138.0,1110.0,1111.9,-0.63,75462,84317711.8,2022,37.42,21.5,14.8,30.0,14.46,2.1,9.1
4,2022-01-06,1111.0,1123.0,1099.6,1114.0,0.19,67780,75380074.6,2022,37.42,21.5,14.8,30.0,14.46,2.1,9.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
964,2026-03-03,508.9,508.9,497.0,504.0,1.00,53465,26848394.6,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
965,2026-03-09,514.0,545.0,514.0,545.0,8.13,4906,2570000.0,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
966,2026-03-10,545.0,555.0,528.0,535.0,-1.87,272000,146200000.0,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
967,2026-03-11,539.0,539.0,525.0,527.0,-1.46,78574,41600000.0,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
968,2026-03-12,522.1,531.7,522.0,529.0,0.38,81850,43200000.0,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:

df = df.copy()
df.to_csv('../../data-companywise/processed_data/NABIL.csv', index = False)