In [1]:
#importing the pandas library
import pandas as pd

In [2]:

#reading the file
df = pd.read_csv('../../data-companywise/raw_data/SAHAS.csv')
df

,published_date,open,high,low,close,per_change,traded_quantity,traded_amount,status
0,12/8/2021,622.3,634.0,594.0,595.0,-6.30,31289,18929146.0,-1
1,12/9/2021,595.0,619.0,572.0,581.0,-2.35,44125,25700423.0,-1
2,12/12/2021,570.1,584.6,545.0,545.0,-6.20,39265,21998112.2,-1
3,12/13/2021,535.0,542.0,500.0,513.0,-5.87,38196,19595979.6,-1
4,12/14/2021,505.0,564.0,505.0,563.0,9.75,14615,7901219.0,1
...,...,...,...,...,...,...,...,...,...
979,3/3/2026,585.0,594.8,577.0,589.0,1.73,234606,138095977.7,1
980,3/9/2026,600.7,624.9,600.7,625.0,6.10,3820,2327000.0,1
981,3/10/2026,638.3,650.0,610.0,625.0,0.03,391000,245400000.0,1
982,3/11/2026,630.0,633.0,607.0,616.0,-1.46,353000,219600000.0,-1
983,3/12/2026,615.0,622.0,610.1,616.0,0.00,172000,105900000.0,0

In [3]:
df.drop(columns = 'status', inplace = True)
df

,published_date,open,high,low,close,per_change,traded_quantity,traded_amount
0,12/8/2021,622.3,634.0,594.0,595.0,-6.30,31289,18929146.0
1,12/9/2021,595.0,619.0,572.0,581.0,-2.35,44125,25700423.0
2,12/12/2021,570.1,584.6,545.0,545.0,-6.20,39265,21998112.2
3,12/13/2021,535.0,542.0,500.0,513.0,-5.87,38196,19595979.6
4,12/14/2021,505.0,564.0,505.0,563.0,9.75,14615,7901219.0
...,...,...,...,...,...,...,...,...
979,3/3/2026,585.0,594.8,577.0,589.0,1.73,234606,138095977.7
980,3/9/2026,600.7,624.9,600.7,625.0,6.10,3820,2327000.0
981,3/10/2026,638.3,650.0,610.0,625.0,0.03,391000,245400000.0
982,3/11/2026,630.0,633.0,607.0,616.0,-1.46,353000,219600000.0
983,3/12/2026,615.0,622.0,610.1,616.0,0.00,172000,105900000.0

In [4]:
# Rename specific columns to the "Perfect Schema"
df = df.rename(columns={
    'published_date': 'date',
    'traded_quantity': 'volume',
    'traded_amount': 'turnover',
    'per_change': 'price_change_pct'
})

In [5]:
df

,date,open,high,low,close,price_change_pct,volume,turnover
0,12/8/2021,622.3,634.0,594.0,595.0,-6.30,31289,18929146.0
1,12/9/2021,595.0,619.0,572.0,581.0,-2.35,44125,25700423.0
2,12/12/2021,570.1,584.6,545.0,545.0,-6.20,39265,21998112.2
3,12/13/2021,535.0,542.0,500.0,513.0,-5.87,38196,19595979.6
4,12/14/2021,505.0,564.0,505.0,563.0,9.75,14615,7901219.0
...,...,...,...,...,...,...,...,...
979,3/3/2026,585.0,594.8,577.0,589.0,1.73,234606,138095977.7
980,3/9/2026,600.7,624.9,600.7,625.0,6.10,3820,2327000.0
981,3/10/2026,638.3,650.0,610.0,625.0,0.03,391000,245400000.0
982,3/11/2026,630.0,633.0,607.0,616.0,-1.46,353000,219600000.0
983,3/12/2026,615.0,622.0,610.1,616.0,0.00,172000,105900000.0

In [6]:

#year column created
df['date'] = pd.to_datetime(df['date'])   # convert first
df['year'] = df['date'].dt.year

In [7]:
df

,date,open,high,low,close,price_change_pct,volume,turnover,year
0,2021-12-08,622.3,634.0,594.0,595.0,-6.30,31289,18929146.0,2021
1,2021-12-09,595.0,619.0,572.0,581.0,-2.35,44125,25700423.0,2021
2,2021-12-12,570.1,584.6,545.0,545.0,-6.20,39265,21998112.2,2021
3,2021-12-13,535.0,542.0,500.0,513.0,-5.87,38196,19595979.6,2021
4,2021-12-14,505.0,564.0,505.0,563.0,9.75,14615,7901219.0,2021
...,...,...,...,...,...,...,...,...,...
979,2026-03-03,585.0,594.8,577.0,589.0,1.73,234606,138095977.7,2026
980,2026-03-09,600.7,624.9,600.7,625.0,6.10,3820,2327000.0,2026
981,2026-03-10,638.3,650.0,610.0,625.0,0.03,391000,245400000.0,2026
982,2026-03-11,630.0,633.0,607.0,616.0,-1.46,353000,219600000.0,2026
983,2026-03-12,615.0,622.0,610.1,616.0,0.00,172000,105900000.0,2026

In [8]:
#filtering the data from 2022
df['date'] = pd.to_datetime(df['date'])
df=df[df['date'].dt.year >= 2022].copy()

In [9]:
df

,date,open,high,low,close,price_change_pct,volume,turnover,year
15,2022-01-02,540.0,565.0,534.2,549.0,0.73,15457,8417646.9,2022
16,2022-01-03,545.0,559.0,539.0,544.0,-0.91,46593,25564459.0,2022
17,2022-01-04,541.0,568.0,536.0,566.0,4.04,27443,15226271.3,2022
18,2022-01-05,565.0,608.0,560.6,580.0,2.47,69522,40744392.3,2022
19,2022-01-06,570.0,608.0,569.0,607.0,4.66,67178,40122758.1,2022
...,...,...,...,...,...,...,...,...,...
979,2026-03-03,585.0,594.8,577.0,589.0,1.73,234606,138095977.7,2026
980,2026-03-09,600.7,624.9,600.7,625.0,6.10,3820,2327000.0,2026
981,2026-03-10,638.3,650.0,610.0,625.0,0.03,391000,245400000.0,2026
982,2026-03-11,630.0,633.0,607.0,616.0,-1.46,353000,219600000.0,2026
983,2026-03-12,615.0,622.0,610.1,616.0,0.00,172000,105900000.0,2026

In [10]:
#resetting index
df.reset_index(drop= True, inplace = True)
df

,date,open,high,low,close,price_change_pct,volume,turnover,year
0,2022-01-02,540.0,565.0,534.2,549.0,0.73,15457,8417646.9,2022
1,2022-01-03,545.0,559.0,539.0,544.0,-0.91,46593,25564459.0,2022
2,2022-01-04,541.0,568.0,536.0,566.0,4.04,27443,15226271.3,2022
3,2022-01-05,565.0,608.0,560.6,580.0,2.47,69522,40744392.3,2022
4,2022-01-06,570.0,608.0,569.0,607.0,4.66,67178,40122758.1,2022
...,...,...,...,...,...,...,...,...,...
964,2026-03-03,585.0,594.8,577.0,589.0,1.73,234606,138095977.7,2026
965,2026-03-09,600.7,624.9,600.7,625.0,6.10,3820,2327000.0,2026
966,2026-03-10,638.3,650.0,610.0,625.0,0.03,391000,245400000.0,2026
967,2026-03-11,630.0,633.0,607.0,616.0,-1.46,353000,219600000.0,2026
968,2026-03-12,615.0,622.0,610.1,616.0,0.00,172000,105900000.0,2026

In [11]:
fundamental_data = {
    'year': [2022, 2023, 2024, 2025], # Corresponding to FY 78/79, 79/80, 80/81, 81/82
    'eps': [0.18, 2.94, 9.10, 23.88],
    'pe-ratio': [3245.0, 185.20, 68.50, 28.50],
    'roe': [0.12, 1.84, 6.94, 13.63],
    'dividend': [0.00, 0.00, 8.42, 22.11],
    'net-margin': [16.99, 26.36, 34.03, 40.04],
    'pb-ratio': [2.80, 3.20, 3.70, 3.40],
    'debt-equity': [2.10, 1.85, 1.60, 1.45]
}
df_fundamental = pd.DataFrame(fundamental_data)
df_fundamental

   year    eps  pe-ratio    roe  dividend  net-margin  pb-ratio  debt-equity
0  2022   0.18    3245.0   0.12      0.00       16.99       2.8         2.10
1  2023   2.94     185.2   1.84      0.00       26.36       3.2         1.85
2  2024   9.10      68.5   6.94      8.42       34.03       3.7         1.60
3  2025  23.88      28.5  13.63     22.11       40.04       3.4         1.45

In [12]:
# merging
df = pd.merge(df, df_fundamental, on='year',how= 'left')
df

,date,open,high,low,close,price_change_pct,volume,turnover,year,eps,pe-ratio,roe,dividend,net-margin,pb-ratio,debt-equity
0,2022-01-02,540.0,565.0,534.2,549.0,0.73,15457,8417646.9,2022,0.18,3245.0,0.12,0.0,16.99,2.8,2.1
1,2022-01-03,545.0,559.0,539.0,544.0,-0.91,46593,25564459.0,2022,0.18,3245.0,0.12,0.0,16.99,2.8,2.1
2,2022-01-04,541.0,568.0,536.0,566.0,4.04,27443,15226271.3,2022,0.18,3245.0,0.12,0.0,16.99,2.8,2.1
3,2022-01-05,565.0,608.0,560.6,580.0,2.47,69522,40744392.3,2022,0.18,3245.0,0.12,0.0,16.99,2.8,2.1
4,2022-01-06,570.0,608.0,569.0,607.0,4.66,67178,40122758.1,2022,0.18,3245.0,0.12,0.0,16.99,2.8,2.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
964,2026-03-03,585.0,594.8,577.0,589.0,1.73,234606,138095977.7,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
965,2026-03-09,600.7,624.9,600.7,625.0,6.10,3820,2327000.0,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
966,2026-03-10,638.3,650.0,610.0,625.0,0.03,391000,245400000.0,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
967,2026-03-11,630.0,633.0,607.0,616.0,-1.46,353000,219600000.0,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
968,2026-03-12,615.0,622.0,610.1,616.0,0.00,172000,105900000.0,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
df = df.copy()
df.to_csv('../../data-companywise/processed_data/SAHAS.csv', index = False)

In [14]:
#PROBLEM SOLUTION:
# git config --global core.autocrlf true