In [23]:
#importing the libraries
import pandas as pd

In [24]:
#reading the file
df = pd.read_csv('../../data-companywise/raw_data/SCB.csv')
df

,published_date,open,high,low,close,per_change,traded_quantity,traded_amount,status
0,6/2/2011,1551.0,1586.0,1550.0,1557.0,NaN,1379,2143240.0,0
1,6/5/2011,1557.0,1560.0,1490.0,1560.0,0.19,3508,5284380.0,0
2,6/6/2011,1560.0,1541.0,1490.0,1541.0,-1.22,1182,1772096.0,0
3,6/7/2011,1541.0,1511.0,1452.0,1474.0,-4.35,420,619870.0,0
4,6/8/2011,1474.0,1475.0,1400.0,1400.0,-5.02,1764,2504733.0,0
...,...,...,...,...,...,...,...,...,...
3379,3/3/2026,647.2,652.0,642.1,650.0,0.43,9794,6356859.7,1
3380,3/9/2026,663.0,699.0,663.0,699.0,7.49,460,313000.0,1
3381,3/10/2026,712.0,712.6,653.0,685.0,-1.96,82493,55700000.0,-1
3382,3/11/2026,698.1,698.1,665.0,665.0,-2.92,12196,8164000.0,-1
3383,3/12/2026,665.0,669.0,660.1,668.0,0.45,21163,14100000.0,1

In [25]:
df.drop(columns = 'status', inplace = True)
df

,published_date,open,high,low,close,per_change,traded_quantity,traded_amount
0,6/2/2011,1551.0,1586.0,1550.0,1557.0,NaN,1379,2143240.0
1,6/5/2011,1557.0,1560.0,1490.0,1560.0,0.19,3508,5284380.0
2,6/6/2011,1560.0,1541.0,1490.0,1541.0,-1.22,1182,1772096.0
3,6/7/2011,1541.0,1511.0,1452.0,1474.0,-4.35,420,619870.0
4,6/8/2011,1474.0,1475.0,1400.0,1400.0,-5.02,1764,2504733.0
...,...,...,...,...,...,...,...,...
3379,3/3/2026,647.2,652.0,642.1,650.0,0.43,9794,6356859.7
3380,3/9/2026,663.0,699.0,663.0,699.0,7.49,460,313000.0
3381,3/10/2026,712.0,712.6,653.0,685.0,-1.96,82493,55700000.0
3382,3/11/2026,698.1,698.1,665.0,665.0,-2.92,12196,8164000.0
3383,3/12/2026,665.0,669.0,660.1,668.0,0.45,21163,14100000.0

In [26]:

# Rename specific columns to the "Perfect Schema"
df = df.rename(columns={
    'published_date': 'date',
    'traded_quantity': 'volume',
    'traded_amount': 'turnover',
    'per_change': 'price_change_pct'
})

In [27]:
df

,date,open,high,low,close,price_change_pct,volume,turnover
0,6/2/2011,1551.0,1586.0,1550.0,1557.0,NaN,1379,2143240.0
1,6/5/2011,1557.0,1560.0,1490.0,1560.0,0.19,3508,5284380.0
2,6/6/2011,1560.0,1541.0,1490.0,1541.0,-1.22,1182,1772096.0
3,6/7/2011,1541.0,1511.0,1452.0,1474.0,-4.35,420,619870.0
4,6/8/2011,1474.0,1475.0,1400.0,1400.0,-5.02,1764,2504733.0
...,...,...,...,...,...,...,...,...
3379,3/3/2026,647.2,652.0,642.1,650.0,0.43,9794,6356859.7
3380,3/9/2026,663.0,699.0,663.0,699.0,7.49,460,313000.0
3381,3/10/2026,712.0,712.6,653.0,685.0,-1.96,82493,55700000.0
3382,3/11/2026,698.1,698.1,665.0,665.0,-2.92,12196,8164000.0
3383,3/12/2026,665.0,669.0,660.1,668.0,0.45,21163,14100000.0

In [28]:
#filtering the data from 2022
df['date'] = pd.to_datetime(df['date'])
df=df[df['date'].dt.year >= 2022].copy()

In [29]:
#resetting index
df.reset_index(drop = True,  inplace= True)
df

,date,open,high,low,close,price_change_pct,volume,turnover
0,2022-01-02,447.0,457.9,439.1,457.9,2.44,16214,7294539.2
1,2022-01-03,466.9,467.0,457.9,462.0,0.90,14593,6735724.1
2,2022-01-04,462.0,508.2,452.8,497.0,7.58,48028,23587557.0
3,2022-01-05,488.0,515.0,482.2,489.0,-1.61,16531,8196669.8
4,2022-01-06,480.0,525.0,480.0,510.0,4.29,31673,15905067.2
...,...,...,...,...,...,...,...,...
964,2026-03-03,647.2,652.0,642.1,650.0,0.43,9794,6356859.7
965,2026-03-09,663.0,699.0,663.0,699.0,7.49,460,313000.0
966,2026-03-10,712.0,712.6,653.0,685.0,-1.96,82493,55700000.0
967,2026-03-11,698.1,698.1,665.0,665.0,-2.92,12196,8164000.0
968,2026-03-12,665.0,669.0,660.1,668.0,0.45,21163,14100000.0

In [30]:
df['year'] = df['date'].dt.year
df

,date,open,high,low,close,price_change_pct,volume,turnover,year
0,2022-01-02,447.0,457.9,439.1,457.9,2.44,16214,7294539.2,2022
1,2022-01-03,466.9,467.0,457.9,462.0,0.90,14593,6735724.1,2022
2,2022-01-04,462.0,508.2,452.8,497.0,7.58,48028,23587557.0,2022
3,2022-01-05,488.0,515.0,482.2,489.0,-1.61,16531,8196669.8,2022
4,2022-01-06,480.0,525.0,480.0,510.0,4.29,31673,15905067.2,2022
...,...,...,...,...,...,...,...,...,...
964,2026-03-03,647.2,652.0,642.1,650.0,0.43,9794,6356859.7,2026
965,2026-03-09,663.0,699.0,663.0,699.0,7.49,460,313000.0,2026
966,2026-03-10,712.0,712.6,653.0,685.0,-1.96,82493,55700000.0,2026
967,2026-03-11,698.1,698.1,665.0,665.0,-2.92,12196,8164000.0,2026
968,2026-03-12,665.0,669.0,660.1,668.0,0.45,21163,14100000.0,2026

In [31]:
#adding the fundamental data
fundamental_data = {
    'year':[2022,2023,2024,2025],
    'eps':[37.36, 43.19, 30.17, 27.35],
    'pe-ratio':[16.51, 14.80, 20.15, 23.03],
    'roe':[14.15, 17.55, 14.30, 12.96],
    'dividend':[16.51, 19.00, 25.50, 19.00],
    'net-margin': [39.19, 44.50, 47.36, 48.12],
    'pb-ratio': [1.85, 2.15, 2.40, 2.55],
    'debt-equity': [6.50, 6.20, 5.80, 5.50]
}
df_fundamental = pd.DataFrame(fundamental_data)
df_fundamental

   year    eps  pe-ratio    roe  dividend  net-margin  pb-ratio  debt-equity
0  2022  37.36     16.51  14.15     16.51       39.19      1.85          6.5
1  2023  43.19     14.80  17.55     19.00       44.50      2.15          6.2
2  2024  30.17     20.15  14.30     25.50       47.36      2.40          5.8
3  2025  27.35     23.03  12.96     19.00       48.12      2.55          5.5

In [32]:

df = pd.merge(df, df_fundamental, on='year',how= 'left')
df

,date,open,high,low,close,price_change_pct,volume,turnover,year,eps,pe-ratio,roe,dividend,net-margin,pb-ratio,debt-equity
0,2022-01-02,447.0,457.9,439.1,457.9,2.44,16214,7294539.2,2022,37.36,16.51,14.15,16.51,39.19,1.85,6.5
1,2022-01-03,466.9,467.0,457.9,462.0,0.90,14593,6735724.1,2022,37.36,16.51,14.15,16.51,39.19,1.85,6.5
2,2022-01-04,462.0,508.2,452.8,497.0,7.58,48028,23587557.0,2022,37.36,16.51,14.15,16.51,39.19,1.85,6.5
3,2022-01-05,488.0,515.0,482.2,489.0,-1.61,16531,8196669.8,2022,37.36,16.51,14.15,16.51,39.19,1.85,6.5
4,2022-01-06,480.0,525.0,480.0,510.0,4.29,31673,15905067.2,2022,37.36,16.51,14.15,16.51,39.19,1.85,6.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
964,2026-03-03,647.2,652.0,642.1,650.0,0.43,9794,6356859.7,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
965,2026-03-09,663.0,699.0,663.0,699.0,7.49,460,313000.0,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
966,2026-03-10,712.0,712.6,653.0,685.0,-1.96,82493,55700000.0,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
967,2026-03-11,698.1,698.1,665.0,665.0,-2.92,12196,8164000.0,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
968,2026-03-12,665.0,669.0,660.1,668.0,0.45,21163,14100000.0,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [33]:
df = df.copy()
df.to_csv('../../data-companywise/processed_data/SCB.csv', index = False)