In [1]:
#importing the pandas library
import pandas as pd

In [2]:
#reading the file
df = pd.read_csv('../../data-companywise/raw_data/SHL.csv')

In [3]:
df

,published_date,open,high,low,close,per_change,traded_quantity,traded_amount,status
0,3/27/2011,237.0,235.0,235.0,235.0,NaN,1239,291165.0,0
1,3/28/2011,235.0,233.0,233.0,233.0,-0.85,100,23300.0,0
2,3/29/2011,233.0,229.0,225.0,225.0,-3.43,1062,239810.0,0
3,3/30/2011,225.0,225.0,225.0,225.0,0.00,123,27675.0,0
4,3/31/2011,225.0,222.0,218.0,218.0,-3.11,644,140836.0,0
...,...,...,...,...,...,...,...,...,...
2979,3/3/2026,496.0,505.0,495.0,501.8,1.17,19351,9677405.6,1
2980,3/9/2026,511.8,532.8,511.8,530.0,5.62,2165,1133000.0,1
2981,3/10/2026,530.0,530.0,503.0,515.0,-2.83,138000,71300000.0,-1
2982,3/11/2026,535.0,539.0,525.0,510.0,-0.97,65828,33700000.0,-1
2983,3/12/2026,503.0,515.0,498.9,511.0,0.20,43826,22400000.0,1

In [4]:
df.drop(columns = 'status', inplace = True)
df

,published_date,open,high,low,close,per_change,traded_quantity,traded_amount
0,3/27/2011,237.0,235.0,235.0,235.0,NaN,1239,291165.0
1,3/28/2011,235.0,233.0,233.0,233.0,-0.85,100,23300.0
2,3/29/2011,233.0,229.0,225.0,225.0,-3.43,1062,239810.0
3,3/30/2011,225.0,225.0,225.0,225.0,0.00,123,27675.0
4,3/31/2011,225.0,222.0,218.0,218.0,-3.11,644,140836.0
...,...,...,...,...,...,...,...,...
2979,3/3/2026,496.0,505.0,495.0,501.8,1.17,19351,9677405.6
2980,3/9/2026,511.8,532.8,511.8,530.0,5.62,2165,1133000.0
2981,3/10/2026,530.0,530.0,503.0,515.0,-2.83,138000,71300000.0
2982,3/11/2026,535.0,539.0,525.0,510.0,-0.97,65828,33700000.0
2983,3/12/2026,503.0,515.0,498.9,511.0,0.20,43826,22400000.0

In [5]:
# Rename specific columns to the "Perfect Schema"
df = df.rename(columns={
    'published_date': 'date',
    'traded_quantity': 'volume',
    'traded_amount': 'turnover',
    'per_change': 'price_change_pct'
})

In [6]:
#year column created
df['date'] = pd.to_datetime(df['date'])   # convert first
df['year'] = df['date'].dt.year

In [7]:
df

,date,open,high,low,close,price_change_pct,volume,turnover,year
0,2011-03-27,237.0,235.0,235.0,235.0,NaN,1239,291165.0,2011
1,2011-03-28,235.0,233.0,233.0,233.0,-0.85,100,23300.0,2011
2,2011-03-29,233.0,229.0,225.0,225.0,-3.43,1062,239810.0,2011
3,2011-03-30,225.0,225.0,225.0,225.0,0.00,123,27675.0,2011
4,2011-03-31,225.0,222.0,218.0,218.0,-3.11,644,140836.0,2011
...,...,...,...,...,...,...,...,...,...
2979,2026-03-03,496.0,505.0,495.0,501.8,1.17,19351,9677405.6,2026
2980,2026-03-09,511.8,532.8,511.8,530.0,5.62,2165,1133000.0,2026
2981,2026-03-10,530.0,530.0,503.0,515.0,-2.83,138000,71300000.0,2026
2982,2026-03-11,535.0,539.0,525.0,510.0,-0.97,65828,33700000.0,2026
2983,2026-03-12,503.0,515.0,498.9,511.0,0.20,43826,22400000.0,2026

In [8]:
#filtering the data from 2022
df['date'] = pd.to_datetime(df['date'])
df = df[df['date'].dt.year > 2022].copy()

In [9]:
#resetting index
df.reset_index(drop= True, inplace = True)
df

,date,open,high,low,close,price_change_pct,volume,turnover,year
0,2023-01-01,217.0,218.9,213.0,214.0,-1.15,39627,8532327.8,2023
1,2023-01-02,214.0,216.8,212.2,214.7,0.33,16700,3586554.8,2023
2,2023-01-03,218.8,227.0,215.2,220.3,2.61,84182,18760003.4,2023
3,2023-01-04,221.0,223.9,215.3,223.0,1.23,27977,6169118.1,2023
4,2023-01-05,225.0,234.9,221.0,233.0,4.48,98676,22374873.2,2023
...,...,...,...,...,...,...,...,...,...
722,2026-03-03,496.0,505.0,495.0,501.8,1.17,19351,9677405.6,2026
723,2026-03-09,511.8,532.8,511.8,530.0,5.62,2165,1133000.0,2026
724,2026-03-10,530.0,530.0,503.0,515.0,-2.83,138000,71300000.0,2026
725,2026-03-11,535.0,539.0,525.0,510.0,-0.97,65828,33700000.0,2026
726,2026-03-12,503.0,515.0,498.9,511.0,0.20,43826,22400000.0,2026

In [10]:
df['year'] = df['date'].dt.year
df

,date,open,high,low,close,price_change_pct,volume,turnover,year
0,2023-01-01,217.0,218.9,213.0,214.0,-1.15,39627,8532327.8,2023
1,2023-01-02,214.0,216.8,212.2,214.7,0.33,16700,3586554.8,2023
2,2023-01-03,218.8,227.0,215.2,220.3,2.61,84182,18760003.4,2023
3,2023-01-04,221.0,223.9,215.3,223.0,1.23,27977,6169118.1,2023
4,2023-01-05,225.0,234.9,221.0,233.0,4.48,98676,22374873.2,2023
...,...,...,...,...,...,...,...,...,...
722,2026-03-03,496.0,505.0,495.0,501.8,1.17,19351,9677405.6,2026
723,2026-03-09,511.8,532.8,511.8,530.0,5.62,2165,1133000.0,2026
724,2026-03-10,530.0,530.0,503.0,515.0,-2.83,138000,71300000.0,2026
725,2026-03-11,535.0,539.0,525.0,510.0,-0.97,65828,33700000.0,2026
726,2026-03-12,503.0,515.0,498.9,511.0,0.20,43826,22400000.0,2026

In [11]:
#adding some fundamental signals
fundamental_data = {
    'year':[2022,2023,2024,2025],
    'eps':[1.95,5.37,6.47,6.56],
    'pe-ratio':[98.4,82.5,78.2,81.7],
    'roe':[11.5,23.4,26.6,25.6],
    'dividend':[26.3,31.5,36.8,31.6],
    'net-margin': [24.73, 26.54, 24.21, 23.81],
    'pb-ratio': [15.20, 18.40, 20.60, 19.42],
    'debt-equity': [0.12, 0.08, 0.04, 0.04]
}
df_fundamental = pd.DataFrame(fundamental_data)
df_fundamental

   year   eps  pe-ratio   roe  dividend  net-margin  pb-ratio  debt-equity
0  2022  1.95      98.4  11.5      26.3       24.73     15.20         0.12
1  2023  5.37      82.5  23.4      31.5       26.54     18.40         0.08
2  2024  6.47      78.2  26.6      36.8       24.21     20.60         0.04
3  2025  6.56      81.7  25.6      31.6       23.81     19.42         0.04

In [12]:
df = pd.merge(df, df_fundamental, on='year',how= 'left')
df

,date,open,high,low,close,price_change_pct,volume,turnover,year,eps,pe-ratio,roe,dividend,net-margin,pb-ratio,debt-equity
0,2023-01-01,217.0,218.9,213.0,214.0,-1.15,39627,8532327.8,2023,5.37,82.5,23.4,31.5,26.54,18.4,0.08
1,2023-01-02,214.0,216.8,212.2,214.7,0.33,16700,3586554.8,2023,5.37,82.5,23.4,31.5,26.54,18.4,0.08
2,2023-01-03,218.8,227.0,215.2,220.3,2.61,84182,18760003.4,2023,5.37,82.5,23.4,31.5,26.54,18.4,0.08
3,2023-01-04,221.0,223.9,215.3,223.0,1.23,27977,6169118.1,2023,5.37,82.5,23.4,31.5,26.54,18.4,0.08
4,2023-01-05,225.0,234.9,221.0,233.0,4.48,98676,22374873.2,2023,5.37,82.5,23.4,31.5,26.54,18.4,0.08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
722,2026-03-03,496.0,505.0,495.0,501.8,1.17,19351,9677405.6,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
723,2026-03-09,511.8,532.8,511.8,530.0,5.62,2165,1133000.0,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
724,2026-03-10,530.0,530.0,503.0,515.0,-2.83,138000,71300000.0,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
725,2026-03-11,535.0,539.0,525.0,510.0,-0.97,65828,33700000.0,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
726,2026-03-12,503.0,515.0,498.9,511.0,0.20,43826,22400000.0,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
df.tail(200)

,date,open,high,low,close,price_change_pct,volume,turnover,year,eps,pe-ratio,roe,dividend,net-margin,pb-ratio,debt-equity
527,2025-04-16,507.9,510.0,495.9,505.39,-0.13,75902,38338935.0,2025,6.56,81.7,25.6,31.6,23.81,19.42,0.04
528,2025-04-17,512.0,515.0,500.3,509.12,0.74,94140,48048389.0,2025,6.56,81.7,25.6,31.6,23.81,19.42,0.04
529,2025-04-20,514.8,515.0,496.4,501.90,-1.42,66230,33526347.3,2025,6.56,81.7,25.6,31.6,23.81,19.42,0.04
530,2025-04-21,499.5,508.0,490.0,501.18,-0.14,60608,30405985.6,2025,6.56,81.7,25.6,31.6,23.81,19.42,0.04
531,2025-04-22,508.9,513.0,498.0,508.23,1.41,107177,54461041.3,2025,6.56,81.7,25.6,31.6,23.81,19.42,0.04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
722,2026-03-03,496.0,505.0,495.0,501.80,1.17,19351,9677405.6,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
723,2026-03-09,511.8,532.8,511.8,530.00,5.62,2165,1133000.0,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
724,2026-03-10,530.0,530.0,503.0,515.00,-2.83,138000,71300000.0,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
725,2026-03-11,535.0,539.0,525.0,510.00,-0.97,65828,33700000.0,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
726,2026-03-12,503.0,515.0,498.9,511.00,0.20,43826,22400000.0,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
df

,date,open,high,low,close,price_change_pct,volume,turnover,year,eps,pe-ratio,roe,dividend,net-margin,pb-ratio,debt-equity
0,2023-01-01,217.0,218.9,213.0,214.0,-1.15,39627,8532327.8,2023,5.37,82.5,23.4,31.5,26.54,18.4,0.08
1,2023-01-02,214.0,216.8,212.2,214.7,0.33,16700,3586554.8,2023,5.37,82.5,23.4,31.5,26.54,18.4,0.08
2,2023-01-03,218.8,227.0,215.2,220.3,2.61,84182,18760003.4,2023,5.37,82.5,23.4,31.5,26.54,18.4,0.08
3,2023-01-04,221.0,223.9,215.3,223.0,1.23,27977,6169118.1,2023,5.37,82.5,23.4,31.5,26.54,18.4,0.08
4,2023-01-05,225.0,234.9,221.0,233.0,4.48,98676,22374873.2,2023,5.37,82.5,23.4,31.5,26.54,18.4,0.08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
722,2026-03-03,496.0,505.0,495.0,501.8,1.17,19351,9677405.6,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
723,2026-03-09,511.8,532.8,511.8,530.0,5.62,2165,1133000.0,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
724,2026-03-10,530.0,530.0,503.0,515.0,-2.83,138000,71300000.0,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
725,2026-03-11,535.0,539.0,525.0,510.0,-0.97,65828,33700000.0,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
726,2026-03-12,503.0,515.0,498.9,511.0,0.20,43826,22400000.0,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
df = df.copy()
df.to_csv('../../data-companywise/processed_data/SHL.csv', index = False)